sarthakroy2002/Scripts

- Kernel/C3_build_script.sh
* guard snippets properly
* fix warns found with shellcheck
* use binutils provided by proton-clang
* rename TANGGAL to DATE
* introduce tg() and tgs() to send messages / files
* refactor send_info() to send detailed info
Signed-off-by: Cyber Knight <cyberknight755@gmail.com>
> Kernel/C3_build_script: Refactor for clarity

- AOSP/aosp-13.sh
- AOSP/cipher-RMX2020.sh
- AOSP/lineage-RMX2020.sh
- AOSP/twrp-build.sh
- Kernel/C3_build_script.sh
- Kernel/C3_eva_kernel.sh
- Kernel/C3_standalonescript.sh
- commit-msg
- personal/ubuntu_envsetup.sh
To maintain a uniform format across all scripts. No functional change.
> scripts: Reformat with shfmt

- AtomX.sh
- personal/arch_post_setup.sh
-> Fixed shebang for portability.
-> Reformatted with shfmt to sync format with our other scripts and solve indentation issues.
> scripts: Reformat the newly added scripts

- AOSP/twrp-build.sh
- Use all available cores
- Make it a bit generic by using variables
Signed-off-by: Sushrut1101 <guptasushrut@gmail.com>
> Improve the TWRP Building script

- Kernel/C3_build_script.sh
Pointless to repeat the same evaluation with two different conditions. Use a logical-OR operator in this case.
Signed-off-by: Tashfin Shakeer Rhythm <tashfinshakeerrhythm@gmail.com>
> scripts: Use logical-OR operator for condition of REPO_URL evaluation

- Kernel/C3_build_script.sh
- Kernel/C3_eva_kernel.sh
- Kernel/C3_standalonescript.sh
Reverts sarthakroy2002/Scripts#16
> Revert "scripts: Avoid regenerating defconfig multiple times"

- Kernel/C3_CI_script.sh
* Based on DroneCI, CirrusCI, CircleCI
Signed-off-by: kawaaii <kawaaii@nocturn9x.space>
> scripts: Add script for building kernel

- personal/setup.sh
- personal/sshid_setup.sh
This is to simplify the setup of the git config in the local machine.
> scripts : added script to setup git config --global

- Kernel/C3_build_script.sh
- Switch to Clang 14.0.0 android-13.0 r450784d
> Fix error Sticker post and Fix LLVM builds

- One-click_setup_for_Mac_Devs.sh
It contains all the commonly used by devs.
> One stop solution for preparing your mac for Dev

- AOSP/404-X00T.sh
Signed-off-by: karthik1896 <karthik1896@outlook.com>
> Add Script for Project 404 X00T

- Kernel/X00T_trb_kernel.sh
Signed-off-by: karthik1896 <karthik1896@outlook.com>
> Add Kernel Compilation Script for X00T

- personal/gentoo.sh
> Add script to setup build environment on Gentoo

- AOSP/AOSP-sync.py
This is a basic script for Syncing the entire Android Open Source Project for building.
> Add Android Open Source Project sync script

- AOSP Scripts/aosp-RMX1941.sh
Signed-off-by: Anoosragh <ok.ano0s6090@gmail.com>
> Add script for PixelExperience-RMX1941

- AOSP Scripts/corvus-r5x.sh
Signed-off-by: Christopher <mizdrake7@gmail.com>
> AOSP: Script to build Corvus for Realme 5 Series

- AOSP Scripts/corvus-r5x.sh
* Saves time and bandwidth so why not ?
Signed-off-by: Christopher <mizdrake7@gmail.com>
> corvus_r5x-script: Use "depth=1" For Repo Init And Sync

- AOSP Scripts/awaken-r5x.sh
1. Make the sync process faster by omitting the commit history
2. Fix syncing of wrong branch i.e a13
> Made necessary changes :-

- Setup/alpine_setup.sh
* Adding more support for different distro setups will help to reach the wider audiences
> scripts: Add script for alpine linux distro

- Setup/zram-setup.sh
1. Copy the script code and save it in a `[zram-setup.sh] file then save it
2. Now run it with `sudo` operation
3. `sudo bash zram-setup.sh`
4. Enter your system password then it will do some operation to install zram and initialize it properly
> Shell: Script to enable zram

- Setup/ubuntu_envsetup.sh
- It is needed for large storage file support
> Scripts: Add git-lfs for installing during setup
